### ISSUE TITLE
How to change the website background in leopard?

### ISSUE THREAD

**Issue by linuzzx** [leopard-js/leopard#111]
I used leopard to convert my scratch game and got rid of the borders which works fine, still you can see separation. I've tried overwriting it with css, didn't work.

[nethunter.html](https://github.com/PullJosh/leopard/files/8237302/nethunter.html.txt)

**Comment by towerofnix** [comment]
I'm not sure this actually has to do with Leopard, a code comment in the file you linked said it was generated with Turbowarp? That's another project by a whole different team of folk. I'm late to this issue anyway, but you'd have to check in with [the developers there](https://github.com/turbowarp) to get the best support relevant to your project.
