### ISSUE TITLE
Variable does not show

### ISSUE THREAD

**Issue by stormqueen23** [leopard-js/leopard#113]
Hi,

I have a small example project here:
https://scratch.mit.edu/projects/584443433/

If I convert it on the leopardjs website the variable is not shown.

The watcher block that was mentioned in #103 is also not there...

I tried to add it manually in stage.js but it does not work either..
this.vars.hunger = 0;
    this.watchers.hunger = new Watcher({
      label: "Hunger",
      visible: true,
      value: () => this.vars.hunger,
      x: -50,
      y: -50
    });

Any tips or ideas what I am doing wrong?

**Comment by towerofnix** [comment]
We did some work on how variable watchers work recently, it looks like this is fixed now! You weren't doing anything wrong, it was just a bug or missing feature in our code.
