### ISSUE TITLE
Policy on external dependencies?

### ISSUE THREAD

**Issue by adroitwhiz** [leopard-js/leopard#128]
IIRC, originally we wanted to avoid using external dependencies to avoid the need for a build step. However, we now have a build step anyway, so how important is it that we can use Leopard without a build step?

It would be useful to import external dependencies like [`gl-matrix`](https://www.npmjs.com/package/gl-matrix) instead of having to essentially vendor the source code.

**Comment by PullJosh** [comment]
Seems reasonable to me. 👍

As long as people can _use_ Leopard without a build step (by importing from unpkg, skypack, etc), I would do whatever makes development easiest.

**Comment by PullJosh** [comment]
@towerofnix You content with allowing external dependencies? If so, I think we can close this issue.

**Comment by towerofnix** [comment]
:+1: No issues here. Makes it easier to manage dependency versioning (e.g. npm audits) as well.
