### ISSUE TITLE
Refactor/document Leopard source code as TypeScript

### ISSUE THREAD

**Issue by towerofnix** [leopard-js/leopard#131]
See a recent comment: https://github.com/leopard-js/leopard/pull/119#discussion_r922909462

> Incorrect method name. Errors when using `this.touching("edge")` while a speech bubble is active.
> 
> (I got very lucky! My test project happened to include this case. We could consider using Typescript to avoid these kinds of errors and also to provide type hints for people using Leopard.)

See also discussion in #128—since we're already working with a build step, it wouldn't add any new steps to the current development workflow.

Bonus reason for writing Leopard in TypeScript: [sb-edit uses TypeScript](https://github.com/leopard-js/sb-edit/tree/master/src), and it's good to be consistent across the two connected codebases!

**Comment by PullJosh** [comment]
I am in favor of this if others are.

**Comment by towerofnix** [comment]
All in favor, react :+1: :)
