### ISSUE TITLE
`this.askAndWait` causes sprite to say `null`

### ISSUE THREAD

**Issue by PullJosh** [leopard-js/leopard#143]
I'm not sure when this bug was introduced, but using `this.askAndWait()` in a sprite causes the sprite to say "null".

<img width="489" alt="image" src="https://user-images.githubusercontent.com/5458180/180661165-10ffe10b-ef60-4062-9b0c-01b35dc97232.png">

**Comment by adroitwhiz** [comment]
Seems to be introduced by https://github.com/leopard-js/leopard/pull/69
