### ISSUE TITLE
Example project is broken

### ISSUE THREAD

**Issue by itrethan** [leopard-js/leopard#152]
after server start, it shows some non sense. Let me know if it's work as intented.

![image](https://user-images.githubusercontent.com/1562799/209286759-651e7ca7-a22c-49fb-8a60-8d78b9a81221.png)

**Comment by towerofnix** [comment]
Yeah sorry, the example project is... *really* weird. It's working as intended.

I think we kind of tested features in there as we were implementing them, and included that in commits, for some reason. Sorry it's very bad! We will probably have real example projects one day in the not so near future!

**Comment by cristian-spiescu** [comment]
I think one should reopen this issue. Because it exists and it's not solved. If there is availability to merge a PR, I could create a quick one. Actually I already needed to copy/paste a project in the repo, to be able to do some debugging in the code.

**Comment by cristian-spiescu** [comment]
I think one should reopen this issue. Because it exists and it's not solved. If there is availability to merge a PR, I could create a quick one. Actually I already needed to copy/paste a project in the repo, to be able to do some debugging in the code.
