### ISSUE TITLE
Any way to manually convert projects?

### ISSUE THREAD

**Issue by veloce-vasta** [leopard-js/leopard#153]
Is there a way to manually configure and be able to use all the leopard functions and convert projects like that for school users who can't access codesandbox due to restrictions from school? If so, can you provide documentation please?

Thanks.

https://scratch.mit.edu/discuss/topic/420162/?page=38#post-6871239
https://scratch.mit.edu/discuss/post/6871248/
https://scratch.mit.edu/discuss/post/6813553/

**Comment by towerofnix** [comment]
We don't have website support for downloading converted projects without CodeSandbox yet, but you can check out sb-edit-playground as a standalone offline tool for generating Leopard projects from Scratch 3.0 projects (sb3 files). It works in the command line so will require some technical ability to set up, which means it may not be applicable to your use case (particularly if you're a teacher working with multiple students). See a quick start guide over here: https://github.com/leopard-js/sb-edit/issues/67#issuecomment-1464082816

We'll probably be adding a "download as zip" feature to the Leopard website sometime down the line. (Currently discussing that and more in #172.) You might still have to use a local web server to run the project, though, which could be tricky to work out on a chromebook or other limited devices.
