### ISSUE TITLE
Improve sequencer/scheduler timing + ordering

### ISSUE THREAD

**Issue by adroitwhiz** [leopard-js/leopard#163]
Right now, there doesn't seem to be much effort put into matching the timing and order of script execution with Scratch. This may be the cause of a large number of compatibility issues.

We should go through the thread-scheduling logic here and compare it with Scratch's (or [my refactoring of it](https://github.com/adroitwhiz/scratch-vm/tree/even-more-sequencer-stuff)) and try to make them match. We can likely reuse many `scratch-vm` execution tests.

**Comment by adroitwhiz** [comment]
Closing this; will create another issue with more detail

**Comment by towerofnix** [comment]
-> #212!
