### ISSUE TITLE
Expose types in package.json

### ISSUE THREAD

**Issue by mybearworld** [leopard-js/leopard#191]
Leopard is written in Typescript, and the type definitions are already part of the Leopard package. However, they aren't actually set in the package.json, so Typescript doesn't see them.

```diff
    "main": "dist/index.umd.js",
    "module": "dist/index.esm.js",
+   "types": "dist/index.d.ts",
```

**Comment by towerofnix** [comment]
@adroitwhiz Pinging you for attention on this, is that all there is to providing Leopard's types to package consumers (what I'm assuming this issue is about)? Pretty much normal for TypeScript projects, no additional changes needed?

**Comment by adroitwhiz** [comment]
Yup, pretty much.

**Comment by towerofnix** [comment]
@mybearworld Would you like to make a pull request? 👾✨

**Comment by mybearworld** [comment]
Sure, I made one.
