### ISSUE TITLE
Should scratch-js implement compatibility functions?

### ISSUE THREAD

**Issue by apple502j** [leopard-js/leopard#58]
Currently, most operators are using JS syntaxes. However, Scratch handles them differently:
* eq, le and gt is case-insensitive
* `(0/0) == (0/0)`
* number expressions are first Number-ed
* different `tan` implementation

Should scratch-js implement those?

**Comment by callowaysutton** [comment]
I think so, the goal of scratch-js is to seamlessly convert scratch projects to js right?

**Comment by towerofnix** [comment]
See my recent pending changes in leopard-js/sb-edit#90. On principle I'm aiming for as best compatibility with Scratch as possible, including compatibility functions where appropriate.
