### ISSUE TITLE
trying to convert a project results in an error

### ISSUE THREAD

**Issue by tjf801** [leopard-js/leopard#80]
Whenever I have tried to convert a scratch project (I have tried it with three different projects from different people, all public), it fails, downloading "codesandbox.json" and having the error "server problem", on at least two different browsers. Any help to get this to work would be greatly appreciated.

**Comment by tjf801** [comment]
Addendum: it seems like every time it tries to load the project, it gets an error 500 in the dev console.

**Comment by PullJosh** [comment]
Hopefully this old is now resolved. If not, let me know.
