### ISSUE TITLE
Problems with my translated project

### ISSUE THREAD

**Issue by proder-app** [leopard-js/leopard#84]
I tried to translate my project https://scratch.mit.edu/projects/459257487/ and found some problems:

1. The text said by the money sprites becomes "null".
2. The sum of the bills is incorrect, for example 1234 becomes 12304.

**Comment by HanClinto** [comment]
I'm guessing that 1230 + 4 being equal to 12304 is because of Javascript's propensity to interpret variables as strings.  We'll need to figure out where this is happening and ensure that it's doing proper numeric conversions first.

**Comment by towerofnix** [comment]
We made a few fixes over the last year or so which address the issues described here, and from testing it looks like this project is working correctly now!
