### ISSUE TITLE
Keeps Saying "Failed - Unknown Server Error"

### ISSUE THREAD

**Issue by zoraizmohammad** [leopard-js/leopard#98]
There seems to be some kind of issue with packaging new scratch projects, please let me know if it can be addressed on my side or your side. Thank you!
![Screenshot 2021-07-13 at 11 50 37 AM](https://user-images.githubusercontent.com/87281838/125484390-1bf80758-e2fb-4b8e-9528-9af338d6dd32.png)

**Comment by PullJosh** [comment]
This is an old issue; hopefully it is resolved now. If not, let me know!
