### ISSUE TITLE
I cant edit my project as JavaScript

### ISSUE THREAD

**Issue by Mikeowsky-2104** [leopard-js/leopard#99]
https://user-images.githubusercontent.com/83537250/125608992-05cb887f-211e-4519-8309-92fa256acea4.mp4

**Comment by PullJosh** [comment]
That is super weird! Thanks for sharing. Maybe it only works if the project is shared? 🤔

**Comment by Mikeowsky-2104** [comment]
> That is super weird! Thanks for sharing. Maybe it only works if the project is shared? 🤔

I will try it

**Comment by Mikeowsky-2104** [comment]
> That is super weird! Thanks for sharing. Maybe it only works if the project is shared? 🤔
@PullJosh 
I tried sharing the project but nope it didn't work I still couldn't edit it as javascript
